// Generated by https://quicktype.io

export interface TranslationFile {
  commands: Commands;
  events: Events;
  menus: Menus;
  generic: Generic;
}

export interface Commands {
  about: About;
  ignoredchannels: Ignoredchannels;
  ignoredroles: Ignoredroles;
  language: Language;
  leaderboard: Leaderboard;
  level: Level;
  levelroles: Levelroles;
  levels: Levels;
  settings: Settings;
  whitelabel: Whitelabel;
  xp: XP;
}

export interface About {
  translators_description: string;
  administrators_description: string;
  developers_description: string;
  owners_description: string;
  bot_description: string;
}

export interface Ignoredchannels {
  channel_already_ignored: string;
  channel_now_ignored: string;
  channel_not_ignored: string;
  channel_now_not_ignored: string;
  channel_list_title: string;
}

export interface Ignoredroles {
  role_already_ignored: string;
  role_now_ignored: string;
  role_not_ignored: string;
  role_now_not_ignored: string;
  role_list_title: string;
}

export interface Language {
  server_language: string;
  user_language: string;
  choice_message: string;
}

export interface Leaderboard {
  leaderboard_title: string;
}

export interface Level {
  not_spoken_yet: string;
  your_current_level: string;
  user_not_spoken_yet: string;
  user_current_level: string;
}

export interface Levelroles {
  role_already_used: string;
  level_must_be_positive: string;
  role_granted: string;
  role_granted_status: string;
  role_granted_status_complete: string;
  role_not_used: string;
  role_removed: string;
}

export interface Levels {
  user_doesnt_exist: string;
  level_to_give_must_be_positive: string;
  levels_added: string;
  level_to_take_must_be_positive: string;
  levels_taken: string;
}

export interface Settings {
  notification_channel_updated: string;
  notification_type_reply_label: string;
  notification_type_reply_description: string;
  notification_type_channel_label: string;
  notification_type_channel_description: string;
  notification_type_dm_label: string;
  notification_type_dm_description: string;
  notification_type_disabled_label: string;
  notification_type_disabled_description: string;
  please_select: string;
  role_type_stacked: string;
  role_type_single: string;
  multiplier_set: string;
  delay_set: string;
}

export interface Whitelabel {
  whitelabel_bot_created_started: string;
  whitelabel_bot_actions: string;
  whitelabel_bot_not_active: string;
}

export interface XP {
  user_doesnt_exist: string;
  xp_to_give_must_be_positive: string;
  xp_added: string;
  xp_to_take_must_be_positive: string;
  xp_taken: string;
}

export interface Events {
  message_create: MessageCreate;
}

export interface MessageCreate {
  message_level_up_reply: string;
  message_level_up_channel: string;
  message_level_up_dm: string;
}

export interface Generic {
  error: string;
  access_denied: string;
}

export interface Menus {
  guild_settings_notifications: GuildSettingsNotifications;
  language_server_menu: LanguageErMenu;
  language_user_menu: LanguageErMenu;
}

export interface GuildSettingsNotifications {
  reply: string;
  channel: string;
  dm: string;
  disable: string;
}

export interface LanguageErMenu {
  language_updated: string;
}
